<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUBQKjAq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUBQKjAq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUBQKjAq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUBQKjAq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUBQKjAq\App_KernelDevDebugContainer([
    'container.build_hash' => 'UBQKjAq',
    'container.build_id' => '76a7b12e',
    'container.build_time' => 1605082992,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUBQKjAq');
